// Constanten + catalogi gebaseerd op intake-template St. Ephrem de Syriër Klooster
// en Unigra-tarievenlijst.

const PAROCHIES = [
  'St. Ephrem de Syriër Klooster — Glane/Losser',
  'Mor Ephrem — Glanerbrug',
  'Mor Severios — Hengelo',
  'Mor Kuryakos — Enschede',
  'Mor Aday — Rijssen',
  'Sint Maria — Amsterdam',
  'Mor Gabriël — Holland',
];

// Vaste tarieven uit het intake-formulier
const KOSTEN_PRESETS = [
  { categorie: 'aannametarief', omschrijving: 'Aannametarief — benodigd personeel en uitvoering', bedrag: 622.00 },
  { categorie: 'vervoer',       omschrijving: 'Ziekenhuismortuarium (Almelo / Enschede)',           bedrag: 146.00 },
  { categorie: 'vervoer',       omschrijving: 'Overbrengen overledene (0–40 km vanaf Oldenzaal)',   bedrag: 231.00 },
  { categorie: 'vervoer',       omschrijving: 'Rouwauto op de dag van de uitvaart',                  bedrag: 242.00 },
  { categorie: 'kist',          omschrijving: 'Basismodel kist (incl. opbaardekentje)',              bedrag: 615.40 },
  { categorie: 'aula',          omschrijving: 'Gebruik aula 3 dagen',                                bedrag: 446.00 },
  { categorie: 'verzorging',    omschrijving: 'Verzorging door extern bedrijf',                      bedrag: 111.00 },
  { categorie: 'verzorging',    omschrijving: 'Inkisten',                                            bedrag:  63.00 },
  { categorie: 'kerk',          omschrijving: 'Gebruik Kerk en Dolabani Zaal',                       bedrag: 500.00 },
  { categorie: 'begraafplaats', omschrijving: 'Openen graf',                                         bedrag: 250.00 },
  { categorie: 'begraafplaats', omschrijving: 'Naamsteen',                                           bedrag: 295.00 },
  { categorie: 'begraafplaats', omschrijving: 'Onderhoudskosten',                                    bedrag: 600.00 },
];

// Unigra kistencatalogus (adviesprijzen per nov 2025)
const KISTEN_CATALOGUS = [
  { naam: 'Natuurkist',                 materiaal: 'Massief populieren, natuur',  bedrag: 1054.00 },
  { naam: 'Natuurkist Wilgenteen',      materiaal: 'Massief populieren, natuur',  bedrag: 1255.50 },
  { naam: '8-10 HC8 Natuur',            materiaal: 'Massief populieren, natuur',  bedrag:  784.50 },
  { naam: '8-10 TC8 Natuur',            materiaal: 'Massief populieren, natuur',  bedrag:  838.00 },
  { naam: '1-70 HC8 Eco',               materiaal: 'Massief eiken, Eco',          bedrag: 1128.00 },
  { naam: '1-70 TC8 Eco',               materiaal: 'Massief eiken, Eco',          bedrag: 1214.00 },
  { naam: '8-10 HC8 Bloemenband',       materiaal: 'Massief populieren, natuur',  bedrag: 1025.00 },
  { naam: '8-10 HC8 Veldbloemen',       materiaal: 'Massief populieren, natuur',  bedrag: 1029.50 },
  { naam: '8-10 HC8 Rustiek',           materiaal: 'Massief populieren, rustiek', bedrag:  864.50 },
  { naam: 'Kleurplaatkist Aan de oever',materiaal: 'Massief populieren, natuur',  bedrag: 1349.50 },
  { naam: 'Kleurplaatkist Sterrenkijken met beren', materiaal: 'Massief populieren', bedrag: 1349.50 },
  { naam: 'Carino HBL2 (2x1) Eiken',    materiaal: 'Massief eiken',               bedrag: 1310.50 },
  { naam: 'Carino HBL2 (2x1) Natuur',   materiaal: 'Massief populieren, natuur',  bedrag: 1147.00 },
  { naam: 'Fiori',                      materiaal: 'Massief populieren, natuur',  bedrag: 1355.00 },
  { naam: '1-50 HBL2 (2x1) Hollands Hout', materiaal: 'Massief grenen',           bedrag: 1257.00 },
  { naam: 'Opbaarplank Hollands Hout',  materiaal: 'Massief grenen',              bedrag: 1017.50 },
  { naam: '1-70 HC8 Hollands Hout',     materiaal: 'Massief eiken',               bedrag: 1244.00 },
  { naam: 'WigRust',                    materiaal: 'Vuren',                       bedrag: 1148.00 },
  { naam: 'Linum Natuur TC8',           materiaal: 'Massief populieren, Eco',     bedrag: 1290.50 },
  { naam: 'GC Rotan Eco Rond',          materiaal: 'Rotan',                       bedrag: 1245.00 },
  { naam: 'GC Bamboe Eco Rond',         materiaal: 'Bamboe',                      bedrag: 1145.00 },
  { naam: 'GC Wilgenteen Cromer',       materiaal: 'Wilgenteen',                  bedrag: 1075.00 },
  { naam: 'UB07 Abaca',                 materiaal: 'Manillahennep',               bedrag: 1295.50 },
  { naam: 'Opbaarplank Abaca',          materiaal: 'Manillahennep',               bedrag:  956.50 },
  { naam: '1-97 HC8 Wild Eiken',        materiaal: 'Houtdecor, wild eiken',       bedrag:  715.50 },
  { naam: '1-90 HC8 Wild Eiken',        materiaal: 'Houtdecor, wild eiken',       bedrag:  579.00 },
  { naam: '1-97 HC8 Naturel',           materiaal: 'Houtdecor, naturel',          bedrag:  715.50 },
  { naam: '1-90 HC8 Naturel',           materiaal: 'Houtdecor, naturel',          bedrag:  579.00 },
  { naam: '1-97 HC8 Wit Wax',           materiaal: 'Houtdecor, wit wax',          bedrag:  715.50 },
  { naam: '1-90 HC8 Wit Wax',           materiaal: 'Houtdecor, wit wax',          bedrag:  579.00 },
  { naam: '1-97 HC8 Grijs Wax',         materiaal: 'Houtdecor, grijs wax',        bedrag:  715.50 },
  { naam: '1-90 HC8 Grijs Wax',         materiaal: 'Houtdecor, grijs wax',        bedrag:  579.00 },
  { naam: '1-20 WHC8',                  materiaal: 'Eikenprint, wit gelakt',      bedrag:  797.50 },
  { naam: '1-20 HC8 RAL',               materiaal: 'Ralkleur gelakt, zijdeglans', bedrag:  964.00 },
  { naam: '1-77 E S',                   materiaal: 'Massief eiken',               bedrag: 1445.00 },
  { naam: '1-70 E S',                   materiaal: 'Massief eiken',               bedrag: 1231.50 },
  { naam: '2-79 G S',                   materiaal: 'Massief eiken, geprofileerd', bedrag: 1615.00 },
  { naam: '2-79 G S Arti Zwart',        materiaal: 'Massief eiken, Arti zwart',   bedrag: 1967.00 },
  { naam: 'La Linea Wit',               materiaal: 'Wit gelakt, zijdeglans',      bedrag: 1895.50 },
  { naam: 'La Linea Zwart',             materiaal: 'Ralkleur gelakt, zijdeglans', bedrag: 1895.50 },
  { naam: 'T10 S',                      materiaal: 'Massief mahonie, geprofileerd', bedrag: 2349.50 },
  { naam: 'T10 S Wit',                  materiaal: 'Wit gelakt, zijdeglans',      bedrag: 2349.50 },
  { naam: 'Hudson',                     materiaal: 'Massief Hout',                bedrag: 4664.00 },
  { naam: 'Da Vinci',                   materiaal: 'Massief Hout',                bedrag: 4664.00 },
  { naam: 'Provincial',                 materiaal: 'Massief Hout',                bedrag: 4664.00 },
];

const STANDAARD_TAKEN = [
  'Familie informeren en intake afnemen',
  'Overlijdensakte opvragen bij gemeente',
  'Parochie en priester aanstellen',
  'Datum en tijd uitvaartdienst vastleggen',
  'Kerk reserveren en koster informeren',
  'Begraafplaats en graf reserveren',
  'Kist bestellen en ophalen',
  'Rouwvervoer regelen (rouwauto + volgauto\'s)',
  'Dragers regelen',
  'Rouwkaarten ontwerpen en versturen',
  'Bloemstukken bestellen',
  'Avondwake / huisbezoek inplannen',
  'Condoleance en catering organiseren',
  'Muziek / zang afstemmen met koor',
  'Aangifte bij Burgerzaken',
  'Verzekering aanmelden',
  'Eindafrekening opstellen',
];

const DOSSIER_VELDEN = [
  'voornaam','achternaam','geslacht','geboortedatum','geboorteplaats',
  'overlijdensdatum','overlijdenstijd','overlijdensplaats',
  'adres_overledene','postcode_overledene','woonplaats_overledene',
  'bsn','burgerlijke_staat','nationaliteit','beroep','doopnaam','syrisch_orthodox_lid',
  'gezinsnummer','grafnummer',
  'contact_naam','contact_voornaam','contact_relatie','contact_telefoon','contact_email',
  'contact_adres','contact_postcode','contact_woonplaats',
  'parochie','priester','huisbezoek_datum','huisbezoek_tijd',
  'avondwake_datum','avondwake_tijd','avondwake_locatie',
  'uitvaart_type','uitvaart_datum','uitvaart_tijd','kerk_locatie',
  'begraafplaats','graf_type',
  'kist_type','rouwauto','aantal_volgauto','dragers','bloemstukken',
  'rouwkaarten_aantal','condoleance_locatie','catering','muziek_zang',
  'verzekering_status','verzekering_maatschappij','polisnummer',
  'opdrachtgever_naam','opdrachtgever_telefoon',
  'bijzonderheden','status'
];
